import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import AppHeader from '@/components/layout/AppHeader';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Stock observer',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${inter.className}`}>
      <body
        className={`pt-20 bg-gray-100 dark:bg-midnight-blue transition-colors duration-500 overflow-hidden h-screen`}
      >
        <AppHeader />
        <div className="flex flex-col h-full">{children}</div>
      </body>
    </html>
  );
}
